# spring:
#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#   devtools:
#     remote:
#       secret: ${DEVTOOLS_SECRET}
#     restart:
#       trigger-file: trigger.txt
      
# spring.flyway.ignore-missing-migrations=true